# Generated by Django 4.2.6 on 2023-10-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissionsentriapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='emissions',
        ),
    ]
